### ISSUE TITLE
Deployment workflow tool? 

### ISSUE THREAD

**Issue by whispercodeDev** [jac3km4/crony-gui#1]
Can you share the tool you used to deploy this project? 
I just tried it with Kubernetes and docker, but the yml file is not compatible with this. 
Sorry, I never deployed with Kubernetes or docker, so a hint would be nice how to use the yml file. Thank you!

**Comment by jac3km4** [comment]
Do you mean the release.yml file?
It's a standard [GitHub workflow file](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions), it basically does 3 things:
- run `cargo build --release`
- download an ASI loader
- create a ZIP archive with the 2 files generated above

**Comment by whispercodeDev** [comment]
Yes, I meant the release.yml. Thanks for the hint, I was thinking way too complicated...... ;)
