### ISSUE TITLE
Deployment errors

### ISSUE THREAD

**Issue by whispercodeDev** [jac3km4/crony-gui#2]
Hi @jac3km4 
Since 0.0.9, there are deployment errors coming when compiling rhai 1.5 (using the github workflow) 
https://github.com/whispertante/crony-gui/actions/runs/2057680020
Can you look into this please? 

E.g.

```
Error:    --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.5.0\src\packages\math_basic.rs:651:62
    |
651 | gen_conversion_as_functions!(num_128_to_int => to_int (i128, u128) -> INT);
    |                                                              ^^^^ not found in this scope
    |
    = note: consider importing this function:
            std::env::args

For more information about this error, try rustc --explain E0425.
```

Adding use std::env::args doesn't work.

**Comment by jac3km4** [comment]
That's strange, it built fine in my action:
https://github.com/jac3km4/crony-gui/actions/runs/2048454110
It builds fine for me locally as well.

**Comment by jac3km4** [comment]
@whispertante you can try removing the cache step from the workflow, it could be causing the issue

**Comment by whispercodeDev** [comment]
Mhm... for the example above I deleted my repo and forked again to have the same build. But it's always failing. 0.0.8 worked though

**Comment by whispercodeDev** [comment]
OK, I will do

**Comment by whispercodeDev** [comment]
Removing the cache step has no effect. 
I will have to look into it later, until now I can't tell what possibly goes wrong 

/edit I close this ticket as it's not related to this repo
